#!/bin/sh

bspc config border_width        1
bspc config window_gap          15

bspc config split_ratio         0.50
bspc config borderless_monocle  false
bspc config gapless_monocle     false
bspc config focus_by_distance   true

#set up the desired amount of workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

#Run compton as a composite manager
if [[ $(pgrep "^compton") ]]; then
	kill $(pgrep "^compton");
fi
compton -cfb &

#run our own custom panel
if [[ $(pgrep "^panel") ]]; then
	pkill panel;
fi
~/.bin/panel &


