#!/bin/sh

bspc config border_width        1
bspc config window_gap         12

bspc config split_ratio         0.50
bspc config borderless_monocle  false
bspc config gapless_monocle     false
bspc config focus_by_distance   true

#Run compton as a composite manager
compton -cfb &
bspc monitor -d I II III IV V VI VII VIII IX X

