#!/bin/sh

bspc config border_width        1
bspc config window_gap          15

bspc config split_ratio         0.50
bspc config borderless_monocle  false
bspc config gapless_monocle     false
bspc config focus_by_distance   true

bspc config presel_feedback_color "#$(getXresColor color1)"
bspc config active_border_color "#$(getXresColor color1)"

#set up the desired amount of workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a URxvt:scratchpad sticky=on state=floating
bspc rule -a URxvt:htop	      sticky=on state=floating
bspc rule -a URxvt:todo	      sticky=on state=floating 
#Run compton as a composite manager
if [[ $(pgrep "^compton") ]]; then
	kill $(pgrep "^compton");
fi
compton -cfb &

feh --bg-fill ~/.wallpapers/.current

#run our own custom panel
if [[ $(pgrep "^panel") ]]; then
	pkill panel;
fi
~/.bin/panel &


