#!/bin/sh
. ~/.bin/panel_colors

num_mon=$(bspc query -M | wc -l)
PADDING=" "

while read -r line; do
	case $line in
		CPU*)
			cpu="$PADDING${line#???}$PADDING"
			;;
		MEM*)
			mem="$PADDING${line#???}$PADDING"
			;;
		BAT*)
			bat="$PADDING${line#???}$PADDING"
			;;
		DATE*)
			#date output
			date="$PADDING${line#????}$PADDING"
			;;
		TIME*)
			#time output
			time="$PADDING${line#????}$PADDING"
			;;
		TITLE*)
			#xtitle output
			if [[ ! -z ${line#?????} ]]; then
				title="%{U$COLOR_UNDERLINE}%{+u}$PADDING${line#?????}$PADDING%{U-}%{-u}"
			else
				title=""
			fi
			;;
		LINK*)
			#wifi link
			link="$PADDING${line#????}$PADDING"
			;;
		W*)
			#bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ]; do item=$1 name=${item#?}
				case $item in
					O*)
						#focused occupied desktop
						wm_infos="${wm_infos}%{U$COLOR_UNDERLINE}%{+u}$PADDING%{F$COLOR_OCCUPIED_FG}${name}%{F-}$PADDING%{-u}%{U-}"
						;;
					F*)
						#focused free desktop
						wm_infos="${wm_infos}%{U$COLOR_UNDERLINE}%{+u}$PADDING%{F$COLOR_FREE_FG}${name}%{F-}$PADDING%{-u}%{U-}"
						;;
					U*)
						#focused urgent desktop
						wm_infos="${wm_infos}%{U$COLOR_UNDERLINE}%{+u}$PADDING${name}$PADDING%{-u}%{U-}"
						;;
					o*)
						#occupied desktop
						wm_infos="${wm_infos}$PADDING%{F$COLOR_OCCUPIED_FG}${name}%{F-}$PADDING"
						;;
					f*)
						#free desktop
						wm_infos="${wm_infos}$PADDING%{F$COLOR_FREE_FG}${name}%{F-}$PADDING"
						;;
					u*)
						#urgent desktop
						wm_infos="${wm_infos}$PADDING${name}$PADDING"
						;;
				esac
				shift
			done
			;;
	esac	
	printf "%s\n" "%{1}${wm_infos}%{c}${title}%{r}${cpu}|${mem}|${link}|${bat}|${date}|${time}"
done

